In [1]:
import numpy as np


In [4]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
question3 = np.arange(0,9).reshape(3,3)
question3


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
question4 = np.nonzero([1,2,0,0,4,0])
question4

(array([0, 1, 4], dtype=int64),)

In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0010537341586481785 0.9924668568656568


In [12]:
Z = np.random.random(10)
m = Z.mean()
print (m)


0.3953020608721868
