Numpy : Practice Problem

1. Extract all odd numbers from arr


In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1::2]

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Convert a 1D array to a 2D array with 2 rows

In [5]:
arr=np.arange(10)
arr.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [6]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Get all items between 5 and 10 from a

In [7]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<10)]

array([6, 9])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [8]:
z = np.zeros(10,int)
z[4]=1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49.

In [9]:
vec = np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
ran = np.random.randint(1,1000,[10,10])
print(ran.min())
print(ran.max())

4
973


9. Create a 3*3 matrix and print it's transpose matrix

In [11]:
ran2 = np.random.randint(1,100,[3,3])
print("3*3 Matrix = \n", ran2)
print("Transpose of 3*3 matrix \n", np.transpose(ran2))

3*3 Matrix = 
 [[72 72 99]
 [77  6 22]
 [34 13 16]]
Transpose of 3*3 matrix 
 [[72 77 34]
 [72  6 13]
 [99 22 16]]


10. Create two arrays of 2-D and find dot product of it.

In [12]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[4,5],[8,9]])
arr1.dot(arr2)

array([[33, 39],
       [72, 87]])

11. Compute the maximum for each row in the given array.

In [13]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print("Matrix = \n",a)
np.max(a,1)

Matrix = 
 [[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [14]:
data = np.random.randint(10,100,(5,4))
print(data)
data[[2,4],[2,3]]

[[25 70 68 26]
 [19 96 12 37]
 [14 41 11 23]
 [93 14 69 77]
 [17 59 57 75]]


array([11, 75])

13. Convert below matrix into vector

In [15]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
np.reshape(matrix,(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

14. The product of two inverse matrix is identical matrix,prove

In [16]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
np.array(np.dot(m,n), dtype=int)

array([[1, 0],
       [0, 1]])

15. Create a matrix from a uniform distribution over [0, 1)

In [17]:
data = np.random.uniform(0,1,(2,2))

In [18]:
data

array([[0.29887635, 0.56874553],
       [0.17862432, 0.5325737 ]])